
package Client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "emailservice", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Emailservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateEmailAddress", targetNamespace = "http://service/", className = "Client.ValidateEmailAddress")
    @ResponseWrapper(localName = "validateEmailAddressResponse", targetNamespace = "http://service/", className = "Client.ValidateEmailAddressResponse")
    @Action(input = "http://service/emailservice/validateEmailAddressRequest", output = "http://service/emailservice/validateEmailAddressResponse")
    public String validateEmailAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://service/", className = "Client.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://service/", className = "Client.SendEmailResponse")
    @Action(input = "http://service/emailservice/sendEmailRequest", output = "http://service/emailservice/sendEmailResponse")
    public String sendEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendEmailBatch", targetNamespace = "http://service/", className = "Client.SendEmailBatch")
    @ResponseWrapper(localName = "sendEmailBatchResponse", targetNamespace = "http://service/", className = "Client.SendEmailBatchResponse")
    @Action(input = "http://service/emailservice/sendEmailBatchRequest", output = "http://service/emailservice/sendEmailBatchResponse")
    public String sendEmailBatch(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
